# Generated by Django 5.2.17 on 2026-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_intel_watcher', '0003_streamkey_live_key_live_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelWatcherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_enabled', models.BooleanField(default=False, help_text='Enable the global Intel Watcher chat on the Intel Viewing page. Unchecked (the default) disables chat site-wide - viewers see the full-width stream area and the chat endpoint stops responding.')),
            ],
            options={
                'verbose_name': 'Intel Watcher settings',
                'verbose_name_plural': 'Intel Watcher settings',
            },
        ),
    ]
